import type { Metadata } from "next";
import "./globals.css";
import { Lato, Montserrat } from 'next/font/google';
import Header from "../components/Header";
import Footer from "../components/Footer";

const lato = Lato({ 
  subsets: ['latin'], 
  weight: ['400', '700'],
  variable: '--font-lato' // Add variable for CSS custom property
});

const montserrat = Montserrat({ 
  subsets: ['latin'], 
  weight: ['400', '700'],
  variable: '--font-montserrat'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable} ${montserrat.variable} antialiased font-lato`}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}